#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-migrations
Version  : 1.2.0
Release  : 4
URL      : https://rubygems.org/downloads/dm-migrations-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-migrations-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-test-unit

%description
= dm-migrations
DataMapper plugin for writing and specing migrations.
== Example

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-migrations-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-migrations.gemspec

%build
gem build rubygem-dm-migrations.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-migrations-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/dm-migrations-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/db/migrations/1_create_people_table.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/db/migrations/2_add_dob_to_people.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/db/migrations/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/dm-migrations.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/examples/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/examples/sample_migration.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/examples/sample_migration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-do-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-mysql-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-oracle-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlite-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-sqlserver-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-yaml-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/exceptions/duplicate_migration.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/migration.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/migration_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql/column.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql/mysql.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql/postgres.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql/sqlite.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql/table_creator.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/dm-migrations/sql/table_modifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/spec/example/migration_example_group.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/lib/spec/matchers/migration_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/integration/auto_migration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/integration/auto_upgrade_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/integration/migration_runner_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/integration/migration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/integration/sql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/isolated/require_after_setup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/isolated/require_before_setup_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/isolated/require_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/rcov.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/spec.opts
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/migration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/sql/column_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/sql/postgres_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/sql/sqlite_extensions_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/sql/table_creator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/sql/table_modifier_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/sql/table_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/spec/unit/sql_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/tasks/spec.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-migrations-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/dm-migrations-1.2.0.gemspec
